# Generated by Django 5.2.1 on 2025-06-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_profile_email_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
