# Generated by Django 5.2.1 on 2025-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
